
server:
  port: 8080

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: first-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: first-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/first-service/management/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/second-service/(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/second-service/management/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/second-service/(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/second-service/post/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/second-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter



management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace
      base-path: /gateway/management