
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://POST-SERVICE
          predicates:
            - name: user-second-service
              - Path=/second-service/**
            - name: management-second-service
              - Path=/second-service/management/**
          filters:
            - name: user-filter-for-user-second-service
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter
            - name: management-filter-for-management-second-service
              - RemoveRequestHeader=Cookie



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace
      base-path: /gateway/management