
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/second-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: second-service
            uri: lb://POST-SERVICE
            predicates:
              - Path=/second-service/management/**
            filters:
              - RemoveRequestHeader=Cookie
              #- RewritePath=/second-service/(?<segment>.*), /$\{segment}


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace
      base-path: /gateway/management